version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./fine_tuned_model:/app/fine_tuned_model

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  blockchain:
    build: ./blockchain
    ports:
      - "7051:7051"
      - "7054:7054"